from __future__ import annotations

import shutil
import subprocess
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

from avacore.tools.notes import Note, list_notes


def _format_note_markdown(note: Note) -> str:
    status_icon = {
        "open": "🟡",
        "done": "✅",
        "archived": "📦",
    }.get(note.status, "•")

    lines = [
        f"### {status_icon} #{note.id} — {note.title}",
        "",
        f"- Status: `{note.status}`",
        f"- Source: `{note.source}`",
        f"- Created: `{note.created_at}`",
        f"- Updated: `{note.updated_at}`",
    ]

    if note.tags:
        lines.append(f"- Tags: `{note.tags}`")

    if note.synced_at:
        lines.append(f"- Synced: `{note.synced_at}`")

    lines.extend(
        [
            "",
            note.content.strip(),
            "",
        ]
    )

    return "\n".join(lines)


def build_notes_markdown(
    db_path: Path | str,
    timezone_name: str = "Europe/Zurich",
    limit: int = 200,
) -> str:
    tz = ZoneInfo(timezone_name)
    now = datetime.now(tz).strftime("%Y-%m-%d %H:%M:%S %Z")

    open_notes = list_notes(db_path=db_path, status="open", limit=limit)
    done_notes = list_notes(db_path=db_path, status="done", limit=limit)
    archived_notes = list_notes(db_path=db_path, status="archived", limit=limit)

    lines: list[str] = [
        "# Ava Notes",
        "",
        f"Last export: `{now}`",
        "",
        "> Generated by AvaCore from local SQLite notes.",
        "",
        "## Open Notes",
        "",
    ]

    if open_notes:
        for note in open_notes:
            lines.append(_format_note_markdown(note))
    else:
        lines.append("_No open notes._")
        lines.append("")

    lines.extend(
        [
            "",
            "## Done Notes",
            "",
        ]
    )

    if done_notes:
        for note in done_notes:
            lines.append(_format_note_markdown(note))
    else:
        lines.append("_No done notes._")
        lines.append("")

    lines.extend(
        [
            "",
            "## Archived Notes",
            "",
        ]
    )

    if archived_notes:
        for note in archived_notes:
            lines.append(_format_note_markdown(note))
    else:
        lines.append("_No archived notes._")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def export_notes_markdown(
    db_path: Path | str,
    export_path: Path | str,
    timezone_name: str = "Europe/Zurich",
) -> Path:
    export_path = Path(export_path).expanduser()
    export_path.parent.mkdir(parents=True, exist_ok=True)

    markdown = build_notes_markdown(
        db_path=db_path,
        timezone_name=timezone_name,
    )

    tmp_path = export_path.with_suffix(export_path.suffix + ".tmp")
    tmp_path.write_text(markdown, encoding="utf-8")
    tmp_path.replace(export_path)

    return export_path


def rclone_copy_file_to_remote(
    local_file: Path | str,
    remote_folder: str,
) -> str:
    local_file = Path(local_file).expanduser()

    if not local_file.exists():
        raise FileNotFoundError(local_file)

    if not remote_folder.strip():
        raise ValueError("rclone remote folder is empty")

    rclone = shutil.which("rclone")
    if not rclone:
        raise RuntimeError("rclone is not installed or not in PATH")

    cmd = [
        rclone,
        "copyto",
        str(local_file),
        remote_folder.rstrip("/") + "/" + local_file.name,
        "--progress",
    ]

    result = subprocess.run(
        cmd,
        check=False,
        capture_output=True,
        text=True,
        timeout=120,
    )

    if result.returncode != 0:
        raise RuntimeError(
            "rclone failed:\n"
            + (result.stderr.strip() or result.stdout.strip() or "unknown error")
        )

    return result.stdout.strip() or "rclone sync completed"


def export_and_sync_notes(
    db_path: Path | str,
    export_path: Path | str,
    timezone_name: str = "Europe/Zurich",
    rclone_enabled: bool = False,
    rclone_remote: str = "",
) -> dict:
    exported_path = export_notes_markdown(
        db_path=db_path,
        export_path=export_path,
        timezone_name=timezone_name,
    )

    result = {
        "exported_path": str(exported_path),
        "rclone_enabled": rclone_enabled,
        "rclone_remote": rclone_remote,
        "rclone_result": "",
    }

    if rclone_enabled:
        result["rclone_result"] = rclone_copy_file_to_remote(
            local_file=exported_path,
            remote_folder=rclone_remote,
        )

    return result